#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3-jdk-11

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build and Test
          trigger: automatic
          caches:
            - maven
          script:
            - mvn clean install --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          trigger: automatic
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelinestegrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.5.1
  branches:
    master: 
      - step:
          name: Build and Test
          trigger: automatic
          artifacts:
            - target/YoutubeDownloader.jar
          caches:
            - maven
          script:
            - mvn clean install --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
    release: 
      - step:
          name: Build and Test
          trigger: automatic
          artifacts:
            - target/YoutubeDownloader.jar
          caches:
            - maven
          script:
            - mvn clean install --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
    refactoring:
      - step:
          name: Build and Test
          trigger: automatic
          caches:
            - maven
          script:
            - mvn clean install --file pom.xml
          after-script:
            # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0